name=SupabaseESP
version=1.0.0
author=Phoovadet
maintainer=Phoovadet
sentence=Supabase client library for ESP32
paragraph=An easy-to-use Supabase client library for ESP32 devices with database, authentication and REST API support.
category=Communication
url=https://github.com/HakusaiTH/SupabaseESP
architectures=esp32
includes=SupabaseESP.h
depends=ArduinoJson, WebSockets
