#ifndef SUPABASE_ERROR_H
#define SUPABASE_ERROR_H

#include <Arduino.h>

/**
 * @brief Error codes generated by SupabaseESP client library.
 */
enum class SupabaseErrorCode {
    NONE = 0,

    INVALID_CONFIG,
    INVALID_URL,
    INVALID_KEY,

    WIFI_NOT_CONNECTED,
    TLS_ERROR,
    HTTP_ERROR,
    TIMEOUT,

    RESPONSE_TOO_LARGE,
    JSON_PARSE_ERROR,

    AUTH_ERROR,
    AUTH_INVALID_CREDENTIALS,
    AUTH_SESSION_EXPIRED,
    AUTH_REFRESH_FAILED,

    STORAGE_ERROR,

    REALTIME_ERROR,
    REALTIME_DISCONNECTED,
    REALTIME_TIMEOUT,
    REALTIME_JOIN_FAILED,

    MUTATION_FILTER_REQUIRED,
    RATE_LIMITED,

    UNKNOWN
};

/**
 * @brief Helper function to convert SupabaseErrorCode to string representation.
 */
inline String supabaseErrorCodeToString(SupabaseErrorCode code) {
    switch (code) {
        case SupabaseErrorCode::NONE:                     return "NONE";
        case SupabaseErrorCode::INVALID_CONFIG:           return "INVALID_CONFIG";
        case SupabaseErrorCode::INVALID_URL:              return "INVALID_URL";
        case SupabaseErrorCode::INVALID_KEY:              return "INVALID_KEY";
        case SupabaseErrorCode::WIFI_NOT_CONNECTED:       return "WIFI_NOT_CONNECTED";
        case SupabaseErrorCode::TLS_ERROR:                return "TLS_ERROR";
        case SupabaseErrorCode::HTTP_ERROR:               return "HTTP_ERROR";
        case SupabaseErrorCode::TIMEOUT:                  return "TIMEOUT";
        case SupabaseErrorCode::RESPONSE_TOO_LARGE:       return "RESPONSE_TOO_LARGE";
        case SupabaseErrorCode::JSON_PARSE_ERROR:         return "JSON_PARSE_ERROR";
        case SupabaseErrorCode::AUTH_ERROR:               return "AUTH_ERROR";
        case SupabaseErrorCode::AUTH_INVALID_CREDENTIALS: return "AUTH_INVALID_CREDENTIALS";
        case SupabaseErrorCode::AUTH_SESSION_EXPIRED:     return "AUTH_SESSION_EXPIRED";
        case SupabaseErrorCode::AUTH_REFRESH_FAILED:      return "AUTH_REFRESH_FAILED";
        case SupabaseErrorCode::STORAGE_ERROR:            return "STORAGE_ERROR";
        case SupabaseErrorCode::REALTIME_ERROR:           return "REALTIME_ERROR";
        case SupabaseErrorCode::REALTIME_DISCONNECTED:    return "REALTIME_DISCONNECTED";
        case SupabaseErrorCode::REALTIME_TIMEOUT:         return "REALTIME_TIMEOUT";
        case SupabaseErrorCode::REALTIME_JOIN_FAILED:     return "REALTIME_JOIN_FAILED";
        case SupabaseErrorCode::MUTATION_FILTER_REQUIRED: return "MUTATION_FILTER_REQUIRED";
        case SupabaseErrorCode::RATE_LIMITED:             return "RATE_LIMITED";
        case SupabaseErrorCode::UNKNOWN:                  return "UNKNOWN";
        default:                                          return "UNKNOWN";
    }
}

#endif // SUPABASE_ERROR_H
